[functions.kiwify-webhook]
verify_jwt = false

[functions.activate-access]
verify_jwt = false

[functions.admin-licenses]
verify_jwt = false

[functions.start-trial]
verify_jwt = false

[functions.first-access]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.sync-recurrence]
verify_jwt = false
